INSERT INTO BANK (id, insert_time, update_time, name, finance_type, company_logo) VALUES (1, CURTIME(), CURTIME(), '신한은행', '1금융권', 'resources/logo/shinhan.png');
INSERT INTO BANK (id, insert_time, update_time, name, finance_type, company_logo) VALUES (2, CURTIME(), CURTIME(), '하나은행', '1금융권', '로고 이미지');
INSERT INTO BANK (id, insert_time, update_time, name, finance_type, company_logo) VALUES (3, CURTIME(), CURTIME(), '국민은행', '1금융권', '로고 이미지');
INSERT INTO BANK (id, insert_time, update_time, name, finance_type, company_logo) VALUES (4, CURTIME(), CURTIME(), '우리은행', '1금융권', '로고 이미지');
INSERT INTO BANK (id, insert_time, update_time, name, finance_type, company_logo) VALUES (5, CURTIME(), CURTIME(), 'SC제일은행', '1금융권', '로고 이미지');
INSERT INTO BANK (id, insert_time, update_time, name, finance_type, company_logo) VALUES (6, CURTIME(), CURTIME(), '경남은행', '1금융권', '로고 이미지');
INSERT INTO BANK (id, insert_time, update_time, name, finance_type, company_logo) VALUES (7, CURTIME(), CURTIME(), '광주은행', '1금융권', '로고 이미지');
INSERT INTO BANK (id, insert_time, update_time, name, finance_type, company_logo) VALUES (8, CURTIME(), CURTIME(), '농협은행', '1금융권', '로고 이미지');
INSERT INTO BANK (id, insert_time, update_time, name, finance_type, company_logo) VALUES (9, CURTIME(), CURTIME(), 'SBI저축은행', '2금융권', '로고 이미지');
INSERT INTO BANK (id, insert_time, update_time, name, finance_type, company_logo) VALUES (10, CURTIME(), CURTIME(), '애큐온저축은행', '2금융권', '로고 이미지');
INSERT INTO BANK (id, insert_time, update_time, name, finance_type, company_logo) VALUES (11, CURTIME(), CURTIME(), '키움YES저축은행', '2금융권', '로고 이미지');
INSERT INTO BANK (id, insert_time, update_time, name, finance_type, company_logo) VALUES (12, CURTIME(), CURTIME(), '현대카드', '카드사', '로고 이미지');
INSERT INTO BANK (id, insert_time, update_time, name, finance_type, company_logo) VALUES (13, CURTIME(), CURTIME(), '롯데카드', '카드사', '로고 이미지');
INSERT INTO BANK (id, insert_time, update_time, name, finance_type, company_logo) VALUES (14, CURTIME(), CURTIME(), '삼성카드', '카드사', '로고 이미지');

INSERT INTO PRODUCT (id, insert_time, update_time, bank_id, product_name, product_category, call_enable) VALUES (1, CURTIME(), CURTIME(), 1, '신한은행 주택담보대출', 'MORTGAGE', 1);
INSERT INTO PRODUCT (id, insert_time, update_time, bank_id, product_name, product_category, call_enable) VALUES (2, CURTIME(), CURTIME(), 2, '하나은행 주택담보대출', 'MORTGAGE', 1);
INSERT INTO PRODUCT (id, insert_time, update_time, bank_id, product_name, product_category, call_enable) VALUES (3, CURTIME(), CURTIME(), 3, '국민은행 주담대론', 'MORTGAGE', 1);
INSERT INTO PRODUCT (id, insert_time, update_time, bank_id, product_name, product_category, call_enable) VALUES (4, CURTIME(), CURTIME(), 4, '우리은행 주택담보대출', 'MORTGAGE', 1);
INSERT INTO PRODUCT (id, insert_time, update_time, bank_id, product_name, product_category, call_enable) VALUES (5, CURTIME(), CURTIME(), 5, 'SC제일은행 주담대론', 'MORTGAGE', 1);
INSERT INTO PRODUCT (id, insert_time, update_time, bank_id, product_name, product_category, call_enable) VALUES (6, CURTIME(), CURTIME(), 6, '경남은행 주택담보대출', 'MORTGAGE', 1);
INSERT INTO PRODUCT (id, insert_time, update_time, bank_id, product_name, product_category, call_enable) VALUES (7, CURTIME(), CURTIME(), 7, '광주은행 주택담보대출', 'MORTGAGE', 1);
INSERT INTO PRODUCT (id, insert_time, update_time, bank_id, product_name, product_category, call_enable) VALUES (8, CURTIME(), CURTIME(), 8, '농협은행 주택담보대출', 'MORTGAGE', 1);
INSERT INTO PRODUCT (id, insert_time, update_time, bank_id, product_name, product_category, call_enable) VALUES (9, CURTIME(), CURTIME(), 9,'SBI저축은행 주택담보대출', 'MORTGAGE', 1);
INSERT INTO PRODUCT (id, insert_time, update_time, bank_id, product_name, product_category, call_enable) VALUES (10, CURTIME(), CURTIME(), 10, '애큐온저축은행 주택담보대출', 'MORTGAGE', 1);
INSERT INTO PRODUCT (id, insert_time, update_time, bank_id, product_name, product_category, call_enable) VALUES (11, CURTIME(), CURTIME(), 11, '키움YES저축은행 주택담보대출', 'MORTGAGE', 1);
INSERT INTO PRODUCT (id, insert_time, update_time, bank_id, product_name, product_category, call_enable) VALUES (12, CURTIME(), CURTIME(), 12, '현대카드 주택담보대출', 'MORTGAGE', 1);
INSERT INTO PRODUCT (id, insert_time, update_time, bank_id, product_name, product_category, call_enable) VALUES (13, CURTIME(), CURTIME(), 13, '롯데카드 주택담보대출', 'MORTGAGE', 1);
INSERT INTO PRODUCT (id, insert_time, update_time, bank_id, product_name, product_category, call_enable) VALUES (14, CURTIME(), CURTIME(), 14, '삼성카드 주택담보대출', 'MORTGAGE', 1);
